import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import prettierConfig from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '.output/**',
      '.wxt/**',
      'node_modules/**',
      'dist/**',
      // wrangler's local dev scratch, written inside site/ by `pnpm site:dev`.
      '**/.wrangler/**',
      // Generated by `wrangler types` from site/wrangler.jsonc — 15k lines of
      // runtime declarations, not ours to lint.
      'site/worker-configuration.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.webextensions,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // The marketing site (site/) is plain static JS outside the extension's
    // own TS/webextension world — just needs browser globals, nothing else
    // above applies to it.
    files: ['site/**/*.js'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },
  {
    // React/hooks rules only apply where React components and hooks actually live.
    files: ['entrypoints/**/*.{ts,tsx}', 'shared/**/*.{ts,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
    },
  },
  prettierConfig,
);
